kind: ReplicationController
apiVersion: v1beta3
metadata:
  name: __rcName__
  labels: &labels
    name: __rcName__
    major: "__major__"
    minor: "__minor__"
    build: "__build__"

spec:
  replicas: __replicas__
  selector: *labels
  template:
    metadata:
      name: __rcName__
      labels: *labels

    spec:
      volumes:
        -  name: secrets
           secret:
             secretName: site-ssl-secret

      containers:
        - name: __rcName__
          image: __image__

          command:
            - "/bin/bash"
            - "/usr/src/start.sh"

          ports:
             - name: __privatePortName1__
               containerPort: __privatePort1__
             - name: __privatePortName2__
               containerPort: __privatePort2__

          env:
            - name: ENABLE_SSL
              value: "true"
            - name: ENABLE_BASIC_AUTH
              value: "true"

          volumeMounts:
            - name: secrets
              readOnly: true
              mountPath: /etc/secrets
