kind: Secret
apiVersion: v1
metadata:
  name: site-ssl-secret
  namespace: default
data:
  htpasswd: YWRhcHRlcnM6JGFwcjEkOHcyak4xWWQkQUR4aWRkZ05OQllZa0M4YkhSSVYwMAoK
  proxycert: >
            LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNKekNDQVpBQ0NRQ1lCUjYrR1Zuam9UQU5C
            Z2txaGtpRzl3MEJBUVVGQURCWU1Rc3dDUVlEVlFRR0V3SkIKVlRFVE1CRUdBMVVFQ0F3S1UyOXRa
            UzFUZEdGMFpURWhNQjhHQTFVRUNnd1lTVzUwWlhKdVpYUWdWMmxrWjJsMApjeUJRZEhrZ1RIUmtN
            UkV3RHdZRFZRUUREQWgzY3kxbWNtOXVkREFlRncweE5UQTJNamt4TkRVMk1qWmFGdzB4Ck5UQTNN
            amt4TkRVMk1qWmFNRmd4Q3pBSkJnTlZCQVlUQWtGVk1STXdFUVlEVlFRSURBcFRiMjFsTFZOMFlY
            UmwKTVNFd0h3WURWUVFLREJoSmJuUmxjbTVsZENCWGFXUm5hWFJ6SUZCMGVTQk1kR1F4RVRBUEJn
            TlZCQU1NQ0hkegpMV1p5YjI1ME1JR2ZNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0R05BRENCaVFLQmdR
            Q3FzUUpiWTBudlpCZkVEVDFzCmhPL0l0R1lCUnJOWlk5Vm9rQkpPdzZzRXVseTJMZ05xdlpFNjJO
            dlJ4QUVkQWZYZFExQ3RNTU01ZkhlWmFNMHEKZURNSmJDZHRkYjFOcm02dlFHRkdsNi83aU5YVFNW
            R0VyYThrc3JxWDhKT3RMYTdIYlFJSHp4NlZOZU1XTVdBaAplRFRRY3hTK0FTQkxNbUtzNi9QdkIx
            bkdXUUlEQVFBQk1BMEdDU3FHU0liM0RRRUJCUVVBQTRHQkFFOGJrZlFJCmFnUEdRaGVsYjdGVWFK
            QnJZKzBKeWVvbEdwQjZGVnRFM0ZCb2tIaVdjNW1MU3QxeFpHcFg4TTNxY1Jsei84L3YKN3FSZWFX
            WVdzVDNtbHZmVG1pUTRqbkU0aXhQT2lQT25RZko5MURGV1hKbWdQalp1N2pXRm5IalMyWVg4ZWV3
            YQpGZU5hNzJqYm9mY1ZNOTV5aGE1bnNvazRYS1ZhamxPbDcwVWMKLS0tLS1FTkQgQ0VSVElGSUNB
            VEUtLS0tLQo=
  proxykey: >
            LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWFFJQkFBS0JnUUNxc1FKYlkwbnZa
            QmZFRFQxc2hPL0l0R1lCUnJOWlk5Vm9rQkpPdzZzRXVseTJMZ05xCnZaRTYyTnZSeEFFZEFmWGRR
            MUN0TU1NNWZIZVphTTBxZURNSmJDZHRkYjFOcm02dlFHRkdsNi83aU5YVFNWR0UKcmE4a3NycVg4
            Sk90TGE3SGJRSUh6eDZWTmVNV01XQWhlRFRRY3hTK0FTQkxNbUtzNi9QdkIxbkdXUUlEQVFBQgpB
            b0dCQUluZlFGQWcrdTlxb2VleDZoTmxyV2tvamR3cUIyUUV4N1FWNnpQRHlMZWc4SklXeUp2SFV5
            OTlTdEU4CnlNbHRjL0t0Rk5WUHRlRVJNR214eFVhd29FZUNVRiszTXlwbDVrUUFjZkhiSmV3dG1m
            VWh3dkN6cmxCK0I2YzUKVjJ6YkNQR0ZKMlFLdzB3Z2NXUkNMbWFEVU5LMGcxcVZXTUU4WG5OWDNO
            T3AyUUFCQWtFQTFqamZBalA3UjhNSgpDUU5abWpYNk1GeHRtS0haSm5ZcGllYU9PbnNtZ2Rkdk93
            OXF0OXlvQ3VKWlpwWlNBYjhrZU1nVzF2TWI0QmNzClZLNThXeFNPV1FKQkFNdjYyWGhIK0VDWkc4
            SGhkRi9TdUhxSFk1OG8vQUdqQzBWKzNCZlVMRFRPNDNGNEtOeHEKZWlFNkRQbStNMWp4bVlsTTda
            elZEMWNZQW5tMmNHOTMrQUVDUUdNeStySCtlRUlHNHN3MXJPeG9TbTdTbmoycgoxTzZta1IyMmtl
            NHEwTzRYWVA2c2FQS3pUMjJhMjJOU0FLK21YN0UrbHJUNjV0R2lhWGpkUStDNWFDRUNRUURDCk1D
            cU9kcjJoQ2VIQi90ZWlUZUp3UzZvTW9LRGhFZzR0OStxaUNNeVk3WWpid2svc0hyWHNJZTZ1WjJO
            TXZweXoKZUhnUlFVaWNXbkFvM1FWSEtVZ0JBa0FYdE9pVDFSd1QveWFLdzdIMFdjWk5qdDhZdEpa
            ekg4RSs5a01tVWN3RAp4Q2I0R2RNNG91Z29GSVVsaDFkRllxMkwwRmpySkZYZktMQnluVEJvT0RP
            cAotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  dhparam: >
            LS0tLS1CRUdJTiBESCBQQVJBTUVURVJTLS0tLS0KTUlJQkNBS0NBUUVBb1hoNGZrbnh5cG5SbkJ4
            dTRlam9OZUVXS3UxWjdkZ3NmcnNSUXc4ZXZkQVpIZ29abkxZSwpLMmN3UitUOG9qbmlidG9oYmxU
            U2NmQlkrbkhNTE8rK2JRMWsvVU5FSVI5N3JtT2lLMVVkUEFoR0FzcHNyeVRjCmxxV1NnZ2twQ2Ix
            RHZQblVSaTdqL3QxalBhMFoxQzlweVdxVDRiU0ZuRGhIZ1dtWnFjaXlnMG13cDVZNjdubWkKeFNQ
            R2xjYXJGTEplT1NvQUFISzdydUliK2padXZBczV0eTlrUktNaG85UkJUcXJWUExFOWFBbWhPVnJr
            V1RyeApZdldieVZiZFNrV2JFQnY0M3FkcmVObUt1blJuU0x0cm0yQmJPRWhGNXRrUU9PeFBkVVk5
            NDhoWmlicFdtM1FNCmdrcWtmdmdSSEJ0R2g0cFlrSFFBOWVFakxRelJtam5VZ3dJQkFnPT0KLS0t
            LS1FTkQgREggUEFSQU1FVEVSUy0tLS0tCg==
